// Explicit fixture for visual review only. Never presented as live data.
export const DEMO_SNAPSHOT = {
  mode: "simulated",
  health: {
    status: "success",
    error: null,
    data: {
      status: "ok",
      timestamp: 1_756_000_000,
      oracle: { symbol: "YPF", status: "valid", source: "data912", lastFetchOkAt: 1_756_000_000 },
      breaker: {
        frozen: false,
        frozenPrice: null,
        frozenAt: null,
        reason: null,
        consecutiveOk: 3,
        thresholdPct: 0.1,
        releaseTicks: 3,
      },
      hip3: { enabled: true, dryRun: true, isTestnet: true, market: "arg:YPF", publishing: false },
      pusher: { enabled: false, contract: null, intervalMs: 30000, lastPushTx: null, lastPushAt: 0 },
    },
  },
  oracle: {
    status: "success",
    error: null,
    data: {
      symbol: "YPF",
      price: 42.315,
      ema: 42.301,
      lastPrint: 42.32,
      bid: 42.3,
      ask: 42.34,
      spread: 0.04,
      reportedCcl: 1180,
      impliedCcl: 1181.2,
      crossCheck: "ok",
      deviation: 0.018,
      pctChange: 1.24,
      status: "valid",
      source: "data912",
      marketOpen: true,
      timestamp: 1_756_000_000,
      lastPrintAt: 1_756_000_000,
      circuitBreaker: {
        frozen: false,
        thresholdPct: 0.1,
        deviation: 0.018,
        releaseTicks: 3,
      },
      raw: {
        data912Status: "connected",
        normalizerStatus: "valid",
        normalizationDetail: "Book normalized",
        sourceStatus: "connected",
      },
    },
  },
  market: {
    status: "success",
    error: null,
    data: {
      symbol: "YPF-PERP",
      markPrice: 42.32,
      indexPrice: 42.315,
      fundingRate: 0.0001,
      maxLeverage: 5,
      marketStatus: "rehearsal",
      oracleStatus: "valid",
      oracleSource: "data912",
      simulated: false,
      hip3: { enabled: true, dryRun: true, isTestnet: true, market: "arg:YPF", publishing: false },
      lastPushTx: null,
      lastPushAt: null,
    },
  },
  fetchedAt: "2026-08-23T03:40:00Z",
};
